apiVersion: v2
name: eden-ui
description: Fineract Backend Application

type: application
version: 0.0.2
appVersion: 1.0.1

dependencies:
  - name: fineract
    version: "0.1.2"
    alias: edens-frontend
    repository: "@fiter-apps"