name: Fiter Latam - Codacy Coverage Reporter
on:
  push:
    branches:
      - fiter/latam/dev
  pull_request:
    branches:
      - fiter/latam/dev
jobs:
  codacy-coverage-reporter:
    name: Run test and upload report
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
           cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
             ${{ runner.os }}-build-${{ env.cache-name }}-
             ${{ runner.os }}-build-
             ${{ runner.os }}-

      - name: Install Dependencies
        # if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
           npm install -g bower
           npm install -g grunt-cli
           bower install
           npm install

      - name: Test coverage
        run: |
          npm test --no-watch --no-progress

      - name: List Files in root directory
        run: ls -R ../

      - name: Add environment variables to .env
        run: |
          echo CODACY_API_TOKEN=${{ secrets.CODACY_API_TOKEN }} >> .env
      
      # ================================================================================================================
      - name: Upload codacy coverage results
        continue-on-error: true
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
          --project-token ${{ secrets.CODACY_API_TOKEN }} \
          --language JavaScript \
          --coverage-reports ../community-app-template/karma-reports/**/lcov.info
          
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: "${{ secrets.CODACY_API_TOKEN }}"
          coverage-reports: ../community-app-template/karma-reports/**/lcov.info

