name: Fiter Latam - Codacy Coverage Reporter
on:
  push:
    branches:
      - fiter/latam/dev
  pull_request:
    branches:
      - fiter/latam/dev
jobs:
  codacy-coverage-reporter:
    name: Run test and upload report
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Cache node modules
      id: cache-nodemodules
      uses: actions/cache@v3
      env:
         cache-name: cache-node-modules
      with:
        # caching node_modules
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
           ${{ runner.os }}-build-${{ env.cache-name }}-
           ${{ runner.os }}-build-
           ${{ runner.os }}-
            
    - name: Install Dependencies
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: |
        npm ci
    
    - name: Build
      run: |
          npm run build -- --prod
    
    - name: Test coverage
      run: |
        npm run test -- --prod
