name: Fiter Latam - Codacy Coverage Reporter
on:
  push:
    branches:
      - fiter/latam/dev
  pull_request:
    branches:
      - fiter/latam/dev
jobs:
  codacy-coverage-reporter:
    name: Run test and upload report
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install -g bower
        npm install -g grunt-cli
        npm install
        grunt test --code-coverage
