name: Fiter Latam - Codacy Coverage Reporter
on:
  push:
    branches:
      - fiter/latam/dev
  pull_request:
    branches:
      - fiter/latam/dev
jobs:
  codacy-coverage-reporter:
    name: Run test and upload report
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Set up Node 12 (package install)
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Remove Node Modules
      run: rm -rf node_modules

    - name: Install Angular CLI
      run: npm install -g @angular/cli@9.1.12

    - name: Update npm
      run: npm update

    - name: Install dependencies
      run: npm install

    - name: Build with NPM
      run: ng build --prod
    
    - name: Test coverage
      run: |
        npm test --code-coverage
        
    - name: List Files in root directory
      run: ls -R ../
        
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        api-token: ${{ secrets.CODACY_API_TOKEN }}
        coverage-reports: ../community-app-template//karma-reports/**/lcov.info

