name: Latam Sonar Analysis Dev
on:
  push:
    branches:
      - fiter/latam/dev
  pull_request:
    types: [opened, synchronize, reopened]
  name: Sonar Latam Workflow
  jobs:
    sonarcloud:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}